spring:
  profiles:
    group:
      local:
        - db-local
      dev:
        - db-dev
      prod:
        - db-prod
    active: local
    include: core, core-db, aws, kobis, server-port
  data:
    web:
      pageable:
        one-indexed-parameters: true

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"

server:
  tomcat:
    mbeanregistry:
      enabled: true

info:
  app:
    name: hello-actuator
    company: yh