spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

---

spring:
  datasource:
    url: jdbc:mysql://13.209.65.232:3306/movie-note?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: movie-note-app
    password: aormfl13@
  config:
    activate:
      on-profile: db-local

---

spring:
  datasource:
    url: jdbc:mysql://3.35.47.230:3306/movie-note?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: movie-note-app
    password: aormfl13@
  config:
    activate:
      on-profile: db-dev